CREATE OR REPLACE FUNCTION DECRYPT_CESAR(P_TEXTO_CIFRADO VARCHAR2,
                                   P_DESLOCAMENTO  NUMBER) RETURN VARCHAR2 IS
  V_TEXTO_ORIGINAL VARCHAR2(4000);
BEGIN
  FOR I IN 1 .. LENGTH(P_TEXTO_CIFRADO) LOOP
    IF ASCII(SUBSTR(P_TEXTO_CIFRADO, I, 1)) BETWEEN 65 AND 90 THEN
      V_TEXTO_ORIGINAL := V_TEXTO_ORIGINAL ||
                          CHR(MOD(ASCII(SUBSTR(P_TEXTO_CIFRADO, I, 1)) - 65 -
                                  P_DESLOCAMENTO + 26,
                                  26) + 65);
    ELSIF ASCII(SUBSTR(P_TEXTO_CIFRADO, I, 1)) BETWEEN 97 AND 122 THEN
      V_TEXTO_ORIGINAL := V_TEXTO_ORIGINAL ||
                          CHR(MOD(ASCII(SUBSTR(P_TEXTO_CIFRADO, I, 1)) - 97 -
                                  P_DESLOCAMENTO + 26,
                                  26) + 97);
    ELSE
      V_TEXTO_ORIGINAL := V_TEXTO_ORIGINAL || SUBSTR(P_TEXTO_CIFRADO, I, 1);
    END IF;
  END LOOP;
  RETURN V_TEXTO_ORIGINAL;
END DECRYPT;
